#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#define FORCE_NKRO

#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          10
#define MOUSEKEY_MAX_SPEED         3
#define MOUSEKEY_TIME_TO_MAX       150
#define MOUSEKEY_WHEEL_DELAY       0
#define MOUSEKEY_WHEEL_INTERVAL    50
#define MOUSEKEY_WHEEL_MAX_SPEED   3
#define MOUSEKEY_WHEEL_TIME_TO_MAX 50

#define PERMISSIVE_HOLD
#define TAPPING_TERM        200
#define TAPPING_TOGGLE      3
#define TAP_HOLD_CAPS_DELAY 50

#undef  LOCKING_SUPPORT_ENABLE
#define NO_ACTION_FUNCTION
#define NO_ACTION_MACRO
#define NO_ACTION_ONESHOT
